#108: adding support to custom pricing configuration in helm chart
opencost/opencost-helm-chart pull request #109
Opened 2023-08-28 12:42 UTC by HoussemCharf

Closes #108

2023-08-31 04:34 UTC, mattray commented
This looks like it duplicates the efforts of https://github.com/opencost/opencost-helm-chart/pull/107. Could you check that patch and see if there's anything in it this one needs? I do like this patch's use use of `opencost.onpremisemode.enabled`, so I'm leaning more towards it after it gets cleaned up.

2023-08-31 04:56 UTC, tamalsaha commented
`opencost.onpremisemode.enabled` is semantically wrong for what I was doing in #107 . 

The metricsConfigs.disabledMetrics is necessary to avoid duplicate KMS v2 metrics.

2023-08-31 08:23 UTC, tamalsaha commented
@HoussemCharf, yes. My pr tackles unrelated issues. Those are not related to onpremises deployment.

2023-09-14 11:18 UTC, toscott requested changes
I love the idea of simplifying the barrier for using custom pricing. Thank you for the suggestion and taking a stab at it!

I've made a few comments. Once addressed we can get this merged.

2023-09-14 11:46 UTC, HoussemCharf commented on charts/opencost/templates/configmap.yaml
> +  default.json: |-
Good catch

2023-09-14 11:50 UTC, HoussemCharf commented on charts/opencost/values.yaml
> +  onpremisemode:
sounds good

2023-09-14 11:50 UTC, HoussemCharf commented on charts/opencost/values.yaml
> +    use_values_map: true
sounds good

2023-09-15 18:56 UTC, toscott commented
Awesome!
I plan to review, retest and get merged tonight

2023-09-16 15:08 UTC, toscott requested changes

2023-09-16 15:08 UTC, toscott commented on charts/opencost/templates/configmap.yaml
> +    {
After the changes, this is still not formatting correctly. The trailing comma is causing parsing issues. 

> ERR error accessing cloud provider configuration: models.CustomPricing.ReadString: expects " or n, but found }, error found in #10 byte of ...| "0.01",

I think we can convert the block directly to json, then quote it.
`  default.json: {{ .Values.opencost.customPricing.costModel | toJson | quote }}`

Taking this approach will require explicit quoting on all of the numeric values in the values.yaml file though. There might be a more elegant approach of course.

2023-09-16 15:08 UTC, toscott commented on charts/opencost/templates/configmap.yaml
While reviewing some of the other pull requests, its clear we are going to end up with multiple configmaps. Planning for the future, can you rename this file to configmap-custom-pricing.yaml? 

Thanks!

2023-09-20 07:58 UTC, HoussemCharf commented on charts/opencost/templates/configmap.yaml
> +    {
I kept reaching the same error with the method mentioned above

2023-09-24 16:20 UTC, toscott approved these changes
The last round of changes appears to be working well! Thanks for the contribution @HoussemCharf. Waiting on the CI flows to finish and I'll get this merged.

2023-09-24 16:28 UTC, merged