Make deployment updateStrategy variable.
opencost/opencost-helm-chart pull request #118
Opened 2023-09-26 09:11 UTC by stefanandres

There are scenarios where the pod can get scraped twice by the ServiceMonitor. This will leave duplicate series in prometheus that may lead to many-to-many queries causing broken grafana dashboards.

With this change updateStrategy can be changed to Recreate for those cases.

2023-10-14 01:40 UTC, toscott requested changes
Hello! Thank you for the contribution. I think this is a great plan and hopefully will help some people out.  I've left a comment to address before we can merge. 

If you are willing to allow edits from maintainers, I can help adjust the version. 
Thanks!

2023-10-14 01:40 UTC, toscott commented on charts/opencost/Chart.yaml
> +appVersion: 1.107.0
I suspect you meant to increment the chart version instead of the appVersion. 

If you can revert this, rebase with main, and bump the chart version. I can try to get this merged.

2023-10-14 10:09 UTC, stefanandres commented on charts/opencost/Chart.yaml
> +appVersion: 1.107.0
Oh yes, good catch. I changed it :)

2023-10-14 10:16 UTC, stefanandres commented
Okay, branch is rebased and conflicts resolved. It should be good now.
Since this is forked an org I cannot enable edits from maintainers unfortunately, but if there is something missing, I am glad to add it :)

Thanks!

2023-10-19 04:21 UTC, mattray approved these changes

2023-10-19 04:35 UTC, merged

2023-10-19 04:35 UTC, mattray commented
Thanks!