feat: `startupProbe` to avoid a long initial delay seconds for liveness probe
opencost/opencost-helm-chart pull request #174
Opened 2024-01-25 15:02 UTC by a7i

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Kubernetes Docs: 

>The kubelet uses startup probes to know when a container application has started. If such a probe is configured, liveness and readiness probes do not start until it succeeds, making sure those probes don't interfere with the application startup. This can be used to adopt liveness checks on slow starting containers, avoiding them getting killed by the kubelet before they are up and running.

2024-01-25 15:03 UTC, a7i commented on charts/opencost/values.yaml
> +      periodSeconds: 20
readiness probe must fail before liveness probe. otherwise container stops receiving traffic and restarts at the same time.

2024-01-25 15:03 UTC, a7i commented on charts/opencost/values.yaml
> +      initialDelaySeconds: 10
ideally you should run readiness as soon as the container comes up

2024-01-25 16:22 UTC, lmello approved these changes
we were having issues in our environment, when we reduced the liveness probe timeout. 

we were having issues in our environment, when we reduced the liveness probe timeout. 
This change will make in the worst case scenario kubernetes wait up to 160 seconds for container start, but it will proceed as soon as the container pass the probe. 

Best case scenario if it starts fast it will wait only 10 seconds. 

This allows kubernetes to wait for the container startup in a more efficient way, soon as the container starts, then it benefits of a faster liveness probe and readiness probe. 

It solves the issues we were having in our environment.

2024-01-25 23:05 UTC, mattray requested changes

2024-01-25 23:05 UTC, mattray commented on charts/opencost/templates/deployment.yaml
> +          readinessProbe:
shouldn't this be a `startupProbe`?

2024-01-25 23:08 UTC, a7i commented on charts/opencost/templates/deployment.yaml
> +          readinessProbe:
good catch! fixed

2024-02-09 05:19 UTC, mattray approved these changes

2024-02-09 05:19 UTC, merged