Add Parquet-Exporter helm chart
opencost/opencost-helm-chart pull request #195
Opened 2024-04-08 06:45 UTC by cklingspor

Moved from https://github.com/opencost/opencost-parquet-exporter/pull/10

Hey everyone,

I've created a first draft of a helm chart for the parquet-exporter. I do not have a setup where I can use AWS as of now, therefore the actual push to a S3 bucket is not yet tested. However, I was able to install the chart and run the cronjob in my minikube.

Used [helm-docs](https://github.com/norwoodj/helm-docs) to create a rough documentation around the chart
The chart itself is relatively straight forward I think
Let me know what you think!

2024-04-08 08:09 UTC, mattray commented on charts/parquet-exporter/Chart.yaml
> +name: parquet-exporter
could we make this "opencost-parquet-exporter"?

2024-04-08 08:10 UTC, mattray commented on charts/parquet-exporter/Chart.yaml
> +description: A Helm chart for Kubernetes
"OpenCost Parquet Exporter"

2024-04-08 08:16 UTC, mattray requested changes

2024-04-08 08:16 UTC, mattray commented on charts/parquet-exporter/README.md
> +# parquet-exporter
Could we make the title and the path `charts/opencost-parquet-exporter` to match the repository?

2024-04-08 08:16 UTC, mattray commented on charts/parquet-exporter/README.md
> +| activeDeadlineSeconds | int | `3600` | Keep job runnig (from start time) for [activeDeadlineSeconds]   |
"running"

2024-04-08 08:16 UTC, mattray commented on charts/parquet-exporter/values.yaml
> +    value: opencost.opencost.svc.cluster.local.
is there supposed to be a trailing "."?

2024-04-08 08:16 UTC, mattray commented on charts/parquet-exporter/Chart.yaml
> +name: parquet-exporter
That will have a ripple effect in the templates, but I prefer the verbosity/specificity

2024-04-11 21:33 UTC, asdfgugus commented on charts/parquet-exporter/templates/_annotations.tpl
add new line at the end

2024-04-12 07:50 UTC, cklingspor commented on charts/parquet-exporter/values.yaml
> +  name: opencost
I took that over from @lmello 's code. I have not looked into the actual requirements for the AWS S3 integration but I have to assume that its there for this purpose. 
The service account is optional however. Would you rather have me remove it from the values yaml or adjust the description to state that its an optional parameter`

2024-04-12 08:29 UTC, asdfgugus commented on charts/parquet-exporter/values.yaml
> +  name: opencost
If the service account is not required, I would leave it empty. Maybe also change the key to existingServiceAccount? Otherwise I would assume that it creates the service account by itself.

2024-04-12 08:34 UTC, cklingspor commented on charts/parquet-exporter/values.yaml
> +  name: opencost
Thank you. Ill change accordingly!

2024-04-12 11:06 UTC, asdfgugus approved these changes
I did not test it on my cluster, but the code LGTM.

2024-04-16 05:26 UTC, mattray reviewed
I think the values need to move to `opencost-parquet-exporter`, but I didn't test.

2024-04-16 05:26 UTC, mattray commented on charts/opencost-parquet-exporter/templates/_annotations.tpl
> +{{- define "parquet-exporter.annotations" -}}
do the "parquet-exporter" references need to be changed to "opencost-parquest-exporter" across the board?

2024-04-16 10:12 UTC, cklingspor commented on charts/opencost-parquet-exporter/templates/_annotations.tpl
> +{{- define "parquet-exporter.annotations" -}}
It would be consistent with actual chart name. I'll update accordingly

2024-04-16 16:07 UTC, cklingspor commented on charts/opencost-parquet-exporter/templates/_annotations.tpl
> +{{- define "parquet-exporter.annotations" -}}
Done

2024-08-21 12:08 UTC, lmello commented
I will review this PR after the change to the parquet export repo is merged. 
we cannot merge this PR before this is done.

2024-08-21 12:09 UTC, lmello requested changes
Please fix the trailling whitespaces:
Error: 1:56 [trailing-spaces] trailing spaces
  Error: 8:22 [trailing-spaces] trailing spaces
  Error: 12:68 [trailing-spaces] trailing spaces
  Error: 27:12 [trailing-spaces] trailing spaces
  Error: 59:209 [trailing-spaces] trailing spaces
  Error: 62:117 [trailing-spaces] trailing spaces

2024-08-27 13:30 UTC, brito-rafa approved these changes
LGTM

2025-01-09 15:23 UTC, lmello requested changes

2025-01-09 15:23 UTC, lmello commented on charts/opencost-parquet-exporter/templates/_annotations.tpl
> +{{- define "parquet-exporter.annotations" -}}
@cklingspor this one was missed in the renaming. please update it to opencost-parquet-exporter

2025-01-15 16:16 UTC, cklingspor commented
@lmello Sorry, for missing this. Done

2025-01-15 22:08 UTC, lmello approved these changes

2025-01-15 22:09 UTC, lmello commented
Thanks @cklingspor, I will merge this.

2025-01-15 22:11 UTC, lmello commented
@cklingspor do you want to be the maintainer of the helm chart ? if yes you can add yourself to the maintainers on it to fix the CI error.  if not, you can add my name on it.

2025-01-16 12:23 UTC, cklingspor commented
> @cklingspor do you want to be the maintainer of the helm chart ? if yes you can add yourself to the maintainers on it to fix the CI error. if not, you can add my name on it.

Sure!  I've added my name. Will add way to contact later.

2025-01-19 17:46 UTC, merged