Option to use existing kubernetes secret
opencost/opencost-helm-chart pull request #196
Opened 2024-04-10 10:47 UTC by mpostument

Hello, with current approach prometheus username and password should be added to values.yml, and helm create secret based on those values. But in case when secret already exist in kubernetes there is no way to use it with opencost helm cahrt. This PR allowing to use existing secrets

2024-04-11 06:23 UTC, asdfgugus commented on charts/opencost/Chart.yaml
> +version: 1.33.4
This is a new feature. Please bump to 1.34.0.

2024-04-11 06:24 UTC, mattray requested changes
If you could bump the version to 1.34.0, we'll merge.

2024-04-11 06:29 UTC, asdfgugus commented on charts/opencost/templates/deployment.yaml
> +            - name: DB_BASIC_AUTH_USERNAME
This part is now duplicate. What about checking if `.Values.opencost.prometheus.existing_secret_name` is set and else if `.Values.opencost.prometheus.secret_name` is set?

2024-04-11 13:15 UTC, mpostument commented
> If you could bump the version to 1.34.0, we'll merge.

Done

2024-04-11 13:20 UTC, mpostument commented on charts/opencost/templates/deployment.yaml
> +            - name: DB_BASIC_AUTH_USERNAME
Not sure i understand logic. Can you share example how you propose to do it?

2024-04-11 21:02 UTC, asdfgugus commented on charts/opencost/templates/deployment.yaml
> +            - name: DB_BASIC_AUTH_USERNAME
Without testing every case, I thought about something like this: 
```YAML
{{- if and .Values.opencost.prometheus.username_key (or .Values.opencost.prometheus.username .Values.opencost.prometheus.existingSecretName) }}
- name: DB_BASIC_AUTH_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ .Values.opencost.prometheus.existingSecretName | default (include "opencost.prometheus.secretname" .) }}
      key: {{ .Values.opencost.prometheus.username_key }}
{{- end }}
```
---
IMHO the key for the existing secret name should be camelCase. But I saw some other snake_case keys in the code.

2024-04-11 21:05 UTC, asdfgugus commented
@mpostument can you combine the two commits for a better traceability?

2024-04-12 12:27 UTC, mpostument commented on charts/opencost/templates/deployment.yaml
> +            - name: DB_BASIC_AUTH_USERNAME
Make sense, will do it

2024-04-12 13:33 UTC, mpostument commented on charts/opencost/templates/deployment.yaml
> +            - name: DB_BASIC_AUTH_USERNAME
Done

2024-04-12 13:33 UTC, mpostument commented
> @mpostument can you combine the two commits for a better traceability?

Done

2024-04-15 14:32 UTC, asdfgugus commented on charts/opencost/README.md
> +| opencost.prometheus.existing_secret_name | string | `nil` | Existing secret name that contains credentials for Prometheus |
run helm-docs again

2024-04-16 11:41 UTC, mpostument commented on charts/opencost/README.md
> +| opencost.prometheus.existing_secret_name | string | `nil` | Existing secret name that contains credentials for Prometheus |
done

2024-04-16 21:03 UTC, asdfgugus approved these changes
LGTM!

2024-04-17 22:56 UTC, mattray approved these changes

2024-04-17 22:56 UTC, merged