feat(artifacthub): push artifacthub-repo.yml file to oci repository
opencost/opencost-helm-chart pull request #216
Opened 2024-07-11 15:48 UTC by asdfgugus

issue reference: https://github.com/artifacthub/hub/issues/3919
docs: https://artifacthub.io/docs/topics/repositories/helm-charts/#oci-support

2024-07-17 19:25 UTC, kranurag7 requested changes

2024-07-17 19:25 UTC, kranurag7 commented on .github/workflows/publish.yml
> +          rm -rf oras_${VERSION}_*.tar.gz oras-install/
We can also use setup-oras directly from upstream.
Ref: https://github.com/oras-project/setup-oras

2024-07-17 19:25 UTC, kranurag7 commented on .github/workflows/publish.yml
> +          oras push registry/namespace/chart-name:artifacthub.io  \
```suggestion
          oras push ghcr.io/opencost/charts/opencost:artifacthub.io \
```

2024-07-17 19:42 UTC, asdfgugus commented on .github/workflows/publish.yml
> +          rm -rf oras_${VERSION}_*.tar.gz oras-install/
Thanks for your review! Silly mistakes... 
This is why you should not push late night...

2024-07-17 19:50 UTC, kranurag7 approved these changes
LGTM, thanks for the quick fixes @asdfgugus

2024-07-17 19:52 UTC, kranurag7 requested changes

2024-07-17 19:52 UTC, kranurag7 commented on .github/workflows/publish.yml
> +          oras-version: 1.2.0
```suggestion
          version: 1.2.0
```

I missed this in first go. This should be version as per the docs. 
Ref: https://github.com/oras-project/setup-oras?tab=readme-ov-file#advanced-usage

Night time for me as well :)

2024-07-17 19:59 UTC, asdfgugus commented on .github/workflows/publish.yml
> +          oras-version: 1.2.0
This time it was autocomplete on my side...
A clear sign to turn that off ;)
Thanks again!

2024-07-17 20:06 UTC, kranurag7 approved these changes
Thanks again, LGTM.

2024-07-29 21:49 UTC, toscott approved these changes

2024-07-29 21:49 UTC, merged