mount nginx.conf as a volume to the frontend container
opencost/opencost-helm-chart pull request #244
Opened 2024-12-26 19:20 UTC by mittal-ishaan

mount `nginx.conf` as a volume to the frontend container. This way we would me moving out of [mounting](https://github.com/opencost/opencost-ui/blob/aa7fbcbc1ad1789ef924851e1128514c1a5bc44d/docker-entrypoint.sh#L22) the nginx.conf to the container when pulling the image in the container as that has permission issues in openshift clusters.

Discussion: https://github.com/opencost/opencost-ui/pull/49#issuecomment-2527030430

Testing left

2025-01-20 02:26 UTC, toscott requested changes
A few comments, but overall looks fine as long as this isn't going to break opencost-ui users. 

Will need to increment the minor version number in the chart to pass the build checks before we can merge.

2025-01-20 02:26 UTC, toscott commented on charts/opencost/templates/deployment.yaml
> +          {{- if .Values.opencost.ui.enabled }}
This whole section (270 - 323) is already wrapped in a check on if the ui is enabled. If there isn't going to be a unique setting to enable the configmap, this is a redundant check.

2025-01-20 02:26 UTC, toscott commented on charts/opencost/templates/configmap-frontend.yaml
> +{{- if .Values.opencost.ui.enabled }}
Is this specific configmap always necessary if opencost ui is enabled? My initial reaction is this should be a separate setting, but as long as its not going to be a breaking change for users I'm ok enabling it by default.

2025-01-20 14:43 UTC, mittal-ishaan commented on charts/opencost/templates/configmap-frontend.yaml
> +{{- if .Values.opencost.ui.enabled }}
This configmap is added during runtime in `opencost-ui` image. Which has write permission issues in openshift environment. This change will not break with opencost-ui `v1.114.0` in which @kastl-ars added an if condition in the entrypoint script [there](https://github.com/opencost/opencost-ui/blob/e1496653bac40db5e5dcce21eb5a6bd55cb25d81/docker-entrypoint.sh#L21-L23). We can get this in after bumping opencost-ui image to 1.114.0 . But as it can break for lower versions, should we keep it under a separate setting, considering that we can release it with ui image bump.

2025-02-03 03:02 UTC, toscott commented
The updates look good on this one to me. We will need a version bump here as well. 

I'm thinking we can just coordinate this merge with #245, doing one version bump to 2.0.0 for both of them though.

2025-03-06 21:17 UTC, ameijer approved these changes
LGTM

2025-03-09 11:24 UTC, mittal-ishaan commented
[Merged](https://github.com/mittal-ishaan/opencost-helm-chart/pull/1) this in https://github.com/opencost/opencost-helm-chart/pull/245 to have a combined major release for `v2.0.0`

2025-03-09 11:24 UTC, closed without merging