feat: add Ingress for opencost UI
opencost/opencost-helm-chart pull request #41
Opened 2023-03-16 17:18 UTC by boniek83

Fixes #32

2023-03-16 21:55 UTC, mkilchhofer requested changes
Hi @boniek83 

I am only a contributor here and not a maintainer so my review is not that relevant ;-)

But I'd add an Ingress template which is almost identical with the `helm create mychart` template/skeleton.
The reason behind this is that OpenCost is per definition supported from Kubernetes versions >1.8:

> **What Kubernetes versions does OpenCost support?**
> OpenCost supports a Kubernetes environment above 1.8.
>
> Source: https://www.opencost.io/docs/FAQ#what-kubernetes-versions-does-opencost-support

Therefore the skeleton would be perfect backward compatible:

```yaml
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "foobar.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
# ...
```

2023-03-22 04:26 UTC, mattray commented
@boniek83 do you want to merge in @mkilchhofer's suggestion? We'll merge afterwards

2023-03-22 10:05 UTC, mkilchhofer commented
> @boniek83 do you want to merge in @mkilchhofer's suggestion? We'll merge afterwards

@mattray where does this statement comes from. Do you still support kubernetes 1.8 as of 2023? ;) 
As the chart does not follow this today.

In kubernetes 1.8, the following APIs are not available:
- Deployment: `apps/v1` is not available (needs to be `apps/v1beta1`)
- ClusterRoles / ClusterRoleBindings: `rbac.authorization.k8s.io/v1` not available (needs to be `rbac.authorization.k8s.io/v1beta1`)
- ...

2023-03-22 10:29 UTC, boniek83 commented
@mattray I can do that, but you don't support kubernetes 1.8 anywhere else in this helm chart, so I wonder if there is a point to that. Things can always be changed later if issue of compatibility pops up, which is not likely IMHO. Additionally is it worth it to support such old versions? Helm chart will get increasingly complicated as it gains more features and as kubernetes versions keep getting bigger.

2023-03-22 20:26 UTC, mattray approved these changes

2023-03-22 20:26 UTC, mattray commented
Sorry, I blanked on that thinking of another recent breaking change and my knee-jerk response was "backwards compatibility good" ;)

2023-03-22 23:35 UTC, boniek83 commented
I will fix conflict tomorrow.

2023-03-24 09:18 UTC, boniek83 commented
@mattray  Maintainers will have to bump helm chart version or should I do it?

2023-03-24 23:59 UTC, mattray commented
@boniek83 you can do it or we (the maintainers) will do it manually after merging. It would make sense for us to automate that too.

2023-03-25 10:38 UTC, mkilchhofer commented
> @boniek83 you can do it or we (the maintainers) will do it manually after merging. It would make sense for us to automate that too.

🤔 I automated it in:
- #35
- #30

Contributors should bump it IMHO. This is the standard workflow for chart contributions in the helm community.

2023-03-25 12:38 UTC, mkilchhofer requested changes
After implementing my proposed changes, please run helm-docs again.

2023-03-25 12:38 UTC, mkilchhofer commented on charts/opencost/values.yaml
> +
Please document all possible values separately:

```suggestion
    ingress:
      # -- Ingress for OpenCost UI
      enabled: false
      # -- Ingress controller which implements the resource
      ingressClassName: ""
      # -- Annotations for Ingress resource
      annotations: {}
        # kubernetes.io/tls-acme: "true"
      # -- A list of host rules used to configure the Ingress
      # @default -- See [values.yaml](values.yaml)
      hosts:
        - host: example.local
          paths:
            - /
      # -- Ingress TLS configuration
      tls: []
        #  - secretName: chart-example-tls
        #    hosts:
        #      - chart-example.local
```

2023-03-27 07:27 UTC, merged